- name: Pull and Run docker image
  hosts: localhost
  tasks:
    - name: Pull Housekeepers-Server image
      docker_image:
        name: dspani/housekeepserver
        source: pull
    - name: Create docker server image
      shell: docker create -it --name Housekeepers-Server dspani/housekeepserver
    - name: Pull Housekeepers-Client image
      docker_image:
        name: dspani/housekeepclient
        source: pull
    - name: Create docker server image
      shell: docker create -it --name Housekeepers-Client dspani/housekeepclient
